// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9Ls19--MmxsXwmWblTZxSnka9B6ZphoQ',
    appId: '1:770545050222:web:18710aa61c47bee51b7c7f',
    messagingSenderId: '770545050222',
    projectId: 'ecommerce-app-1744c',
    authDomain: 'ecommerce-app-1744c.firebaseapp.com',
    storageBucket: 'ecommerce-app-1744c.appspot.com',
    measurementId: 'G-JRRDQ51X30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoh5OwXDqV7euO91Hfye0bR9hYfJxlnXc',
    appId: '1:770545050222:android:7e88650e47cf7b461b7c7f',
    messagingSenderId: '770545050222',
    projectId: 'ecommerce-app-1744c',
    storageBucket: 'ecommerce-app-1744c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8JwckZmjskM4Co-N6FYZfaFA6Wy760Ek',
    appId: '1:770545050222:ios:f392c5334b1a2d541b7c7f',
    messagingSenderId: '770545050222',
    projectId: 'ecommerce-app-1744c',
    storageBucket: 'ecommerce-app-1744c.appspot.com',
    androidClientId: '770545050222-e5q11enmffrdiub02pallbds9spbr0s0.apps.googleusercontent.com',
    iosClientId: '770545050222-1h01jhguck834n27vljll0dmujrt04pc.apps.googleusercontent.com',
    iosBundleId: 'com.example.uberApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8JwckZmjskM4Co-N6FYZfaFA6Wy760Ek',
    appId: '1:770545050222:ios:f392c5334b1a2d541b7c7f',
    messagingSenderId: '770545050222',
    projectId: 'ecommerce-app-1744c',
    storageBucket: 'ecommerce-app-1744c.appspot.com',
    androidClientId: '770545050222-e5q11enmffrdiub02pallbds9spbr0s0.apps.googleusercontent.com',
    iosClientId: '770545050222-1h01jhguck834n27vljll0dmujrt04pc.apps.googleusercontent.com',
    iosBundleId: 'com.example.uberApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9Ls19--MmxsXwmWblTZxSnka9B6ZphoQ',
    appId: '1:770545050222:web:0110d0eee86830691b7c7f',
    messagingSenderId: '770545050222',
    projectId: 'ecommerce-app-1744c',
    authDomain: 'ecommerce-app-1744c.firebaseapp.com',
    storageBucket: 'ecommerce-app-1744c.appspot.com',
    measurementId: 'G-ZVRE75VR8G',
  );
}
